version: '3'
services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    volumes:
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://your_db_host:your_db_port/your_db_name
      SONARQUBE_JDBC_USERNAME: your_db_user
      SONARQUBE_JDBC_PASSWORD: your_db_password
